#!/bin/sh
# /etc/init.d/sc_serv: start the shoutcast sc_serv server

### BEGIN INIT INFO
# Provides sc_serv
# Required-Start: $bootmisc $net $localmount
# Required-Stop: $bootmisc $localmount
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start sc_serv
# Description:
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin

SERVPATH=/home/tech-noid/shoutcast/sc_serv
SERVCONF=/home/tech-noid/shoutcast/tech-noid-64.conf
SERVPID=/home/tech-noid/shoutcast/run/tech-noid-64.pid

sc_serv_start() {
    echo "Starting Shoutcast Server - Tech-Noid Relay - 64k"
    start-stop-daemon --start --exec $SERVPATH $SERVCONF --background --make-pidfile --pidfile $SERVPID --name Tech-Noid-Relay-64k
}

sc_serv_stop() {
    echo "Shutting Down Shoutcast Server - Tech-Noid Relay - 64k"
    start-stop-daemon --stop --exec $SERVPATH --pidfile $SERVPID
}


sc_serv_restart() {
    sc_serv_stop
    sc_serv_start
}

case "$1" in
    'start')
        sc_serv_start
        ;;
    'stop')
        sc_serv_stop
        ;;
    'restart')
        sc_serv_restart
        ;;
    *)
        sc_serv_start
esac
